koding/kd

package.json
Development dependencies should be defined in `devDependencies` section
=> npm: devDependencies

package.json
=> npm: pin coffee-script@1.8.0

package.json
=> Revert "npm: devDependencies"

package.json, src/components/dialog/dialogview.coffee
@sinan, can you please merge it?
=> dialog: close dialog on ESC

.gitignore, lib/components/modals/modalview.coffee, lib/components/tabs/tabview.coffee, package.json
=> remove modal content auto max height 

package.json, src/components/modals/modalview.coffee
https://github.com/koding/kd/pull/121 same thing
=> remove modal content auto max height

lib/components/tabs/tabhandleview.coffee, lib/components/tabs/tabpaneview.coffee, lib/components/tabs/tabview.coffee, lib/core/view.coffee
=> View's droppable attribute is optional

lib/components/tabs/tabhandleview.coffee
=> Set default false to options.droppable for TabHandleView

lib/components/tabs/tabhandleview.coffee, lib/core/view.coffee
/cc @sinan @usirin @fatihacet @gokmen
=> Remove 'droppable' attribute.

lib/components/scrollview/customscrollviewinner.coffee, lib/components/scrollview/scrollview.coffee, package.json
@sinan, can you review this fix? It adds a smooth animation to keyboard scrolling. Here is the [task](https://www.pivotaltracker.com/story/show/95597330) in Pivotal
=> custom scroll: keyboard scroll animation [#95597330]

lib/components/scrollview/customscrollviewinner.coffee, package.json
@sinan, can you please review this fix? It's for the task to add support of arrow keys in custom scroll view
=> custom scroll: up and down arrow keys support

lib/core/view.coffee
=> View: Events: Give support dragEnd event for HTML5 DnD now.

lib/components/tabs/tabhandleview.coffee, lib/components/tabs/tabview.coffee, package.json
/cc @gokmen @sinan @fatihacet @szkl
=> TabHandleView: Add sub view to close-tab icon.

lib/styles/helpers.css
/cc @szkl @fatihacet @gokmen @sinan
=> CSS: Helpers: Remove custom IE6 / 7 hacks.

package.json
=> Bump up version to 1.1.14

lib/components/scrollview/customscrollview.coffee, package.json
/cc @sinan @fatihacet @szkl @gokmen
=> CustomScrollView: Update indicators when any mutation happened

lib/components/tabs/tabview.coffee, package.json
And this pr contains bump up version.
/cc @sinan
=> Components: Tabs: TabView: Calculate width of tab handles correctly

lib/components/autocomplete/autocomplete.coffee, package.json
/cc @sinan @usirin @fatihacet @gokmen @szkl
=> Fix autocomplete issue

lib/styles/default/kd.input.styl, package.json
This is mainly due to koding/koding#8776
/cc @sinan
=> Remove image reference

lib/components/loader/loaderview.coffee, lib/core/view.coffee, package.json
cc/ @usirin 
with this i can do:
=> allow entry point from any dom element

examples/pistachio/index.html, examples/pistachio/pistachio.js, lib/core/pistachio.coffee
Details can be found in here https://github.com/koding/kd/blob/a6dc1720d5fdd218feaa426e63e820575d63c287/lib/core/pistachio.coffee#L110-L150
=> Pistachio: simple compare support with in templates
